#!/usr/bin/env python3
import sys
import time
import tensorflow as tf
from tensorflow import keras
import numpy as np
import boto3
import json
import os
import io

print('Arguments received:', str(sys.argv))
print('Env variables',os.environ)

if (len(sys.argv) > 2):
	s3 = boto3.client('s3')
	s3_bucket = 'course-pdl-batch-example'
	result = s3.get_object(Bucket=s3_bucket, Key=sys.argv[1])
	parameters = json.loads(result["Body"].read().decode())
	print(parameters)
	parameters['output'] = 'Current time is ' + str(time.time())
	print(parameters)
	s3.upload_fileobj(io.BytesIO(json.dumps(parameters).encode('utf-8')), s3_bucket, sys.argv[2])

sys.exit(0)
